version: '3.8'

services:
  app:
    build: .
    command: uvicorn main:app --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db  # Aplikacja zależy teraz także od bazy danych PostgreSQL
    volumes:
      - .:/app
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}  # Port PostgreSQL

# Definicja woluminów (dane Postgres będą zapisywane)
volumes:
  postgres_data:
