"""new tables

Revision ID: 0d6b02c3a421
Revises: 
Create Date: 2024-12-22 00:33:48.016320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6b02c3a421'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bucketName', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('originalName', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('createUp', sa.DateTime(), nullable=True),
    sa.Column('updateUp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('createUp', sa.DateTime(), nullable=True),
    sa.Column('updateUp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('createUp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    op.drop_table('file')
    op.drop_table('catalog')
    # ### end Alembic commands ###
