"""init

Revision ID: 51030edf4c34
Revises: 
Create Date: 2024-12-22 13:22:01.652047

"""
from typing import Sequence, Union
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from config.config_app import KEYS_SQL

# revision identifiers, used by Alembic.
revision: str = '51030edf4c34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bucketName', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('originalName', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('createUp', sa.DateTime(), nullable=True),
    sa.Column('updateUp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('createUp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('catalog_id', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('s3_path', sa.String(), nullable=True),
    sa.Column('createUp', sa.DateTime(), nullable=True),
    sa.Column('updateUp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    sql_file_path = os.path.join(KEYS_SQL, "keys.sql")
    with open(sql_file_path, "r") as f:
        op.execute(f.read())

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('keys')
    op.drop_table('catalog')
    # ### end Alembic commands ###
